<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>clearpath_outdoornav_api_lib</name>
  <version>2.3.0</version>
  <description>A library of ROS2 endpoint wrappers to ease OutdoorNav APi development</description>
  <maintainer email="jmastrangelo@clearpathrobotics.com">jmastrangelo</maintainer>
  <license>BSD</license>

  <depend>clearpath_outdoornav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
