# Action definition for undocking a Clearpath UGV from one of its charging docks.

# goal
string dock_name
string map_uuid

---
# result
bool success
string message
uint16 NONE=0
uint16 error_code
string error_msg
---
# feedback
string message
clearpath_navigation_msgs/MissionSegment plan
float32 elapsed_time